#############################################################################
# Makefile for building: ../bin/al-anvar
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Nov 18 14:01:41 2012
# Project:  al-anvar.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile al-anvar.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -w -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -w -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/phonon -I/usr/include/qt4 -I../build -I/usr/include/qt4/phonon_compat -I../build -I../build
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -ldl -lphonon -lQtSql -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ../build/

####### Files

SOURCES       = anvar.cpp \
		main.cpp \
		sqlite3.c \
		setting.cpp \
		addons.cpp \
		ayeexplor.cpp \
		langdialog.cpp \
		sendermail/smtpclient.cpp \
		sendermail/quotedprintable.cpp \
		sendermail/mimetext.cpp \
		sendermail/mimepart.cpp \
		sendermail/mimemessage.cpp \
		sendermail/mimeinlinefile.cpp \
		sendermail/mimehtml.cpp \
		sendermail/mimefile.cpp \
		sendermail/mimeattachment.cpp \
		sendermail/emailaddress.cpp \
		contactform.cpp \
		moshafwidget.cpp \
		editordering.cpp \
		adddirdialog.cpp ../build/moc_anvar.cpp \
		../build/moc_tools.cpp \
		../build/moc_dbsearch.cpp \
		../build/moc_quranwidget.cpp \
		../build/moc_setting.cpp \
		../build/moc_dbtreeview.cpp \
		../build/moc_dbmodel.cpp \
		../build/moc_findreplace.cpp \
		../build/moc_player.cpp \
		../build/moc_Downloader.cpp \
		../build/moc_helpWindow.cpp \
		../build/moc_addons.cpp \
		../build/moc_ayeexplor.cpp \
		../build/moc_langdialog.cpp \
		../build/moc_smtpclient.cpp \
		../build/moc_quotedprintable.cpp \
		../build/moc_mimepart.cpp \
		../build/moc_mimehtml.cpp \
		../build/moc_mimefile.cpp \
		../build/moc_mimeattachment.cpp \
		../build/moc_emailaddress.cpp \
		../build/moc_contactform.cpp \
		../build/moc_moshafwidget.cpp \
		../build/moc_editordering.cpp \
		../build/moc_adddirdialog.cpp \
		qrc_rc.cpp
OBJECTS       = ../build/anvar.o \
		../build/main.o \
		../build/sqlite3.o \
		../build/setting.o \
		../build/addons.o \
		../build/ayeexplor.o \
		../build/langdialog.o \
		../build/smtpclient.o \
		../build/quotedprintable.o \
		../build/mimetext.o \
		../build/mimepart.o \
		../build/mimemessage.o \
		../build/mimeinlinefile.o \
		../build/mimehtml.o \
		../build/mimefile.o \
		../build/mimeattachment.o \
		../build/emailaddress.o \
		../build/contactform.o \
		../build/moshafwidget.o \
		../build/editordering.o \
		../build/adddirdialog.o \
		../build/moc_anvar.o \
		../build/moc_tools.o \
		../build/moc_dbsearch.o \
		../build/moc_quranwidget.o \
		../build/moc_setting.o \
		../build/moc_dbtreeview.o \
		../build/moc_dbmodel.o \
		../build/moc_findreplace.o \
		../build/moc_player.o \
		../build/moc_Downloader.o \
		../build/moc_helpWindow.o \
		../build/moc_addons.o \
		../build/moc_ayeexplor.o \
		../build/moc_langdialog.o \
		../build/moc_smtpclient.o \
		../build/moc_quotedprintable.o \
		../build/moc_mimepart.o \
		../build/moc_mimehtml.o \
		../build/moc_mimefile.o \
		../build/moc_mimeattachment.o \
		../build/moc_emailaddress.o \
		../build/moc_contactform.o \
		../build/moc_moshafwidget.o \
		../build/moc_editordering.o \
		../build/moc_adddirdialog.o \
		../build/qrc_rc.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_off.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		al-anvar.pro
QMAKE_TARGET  = al-anvar
DESTDIR       = ../bin/
TARGET        = ../bin/al-anvar

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ../build/ui_anvar.h ../build/ui_setting.h ../build/ui_addons.h ../build/ui_ayeexplor.h ../build/ui_langdialog.h ../build/ui_player.h ../build/ui_quranwidget.h ../build/ui_contactform.h ../build/ui_moshafwidget.h ../build/ui_editordering.h ../build/ui_adddirdialog.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ../bin/ || $(MKDIR) ../bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: al-anvar.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_off.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/i386-linux-gnu/libQtSql.prl \
		/usr/lib/i386-linux-gnu/libQtXml.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile al-anvar.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_off.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/i386-linux-gnu/libQtSql.prl:
/usr/lib/i386-linux-gnu/libQtXml.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile al-anvar.pro

dist: 
	@$(CHK_DIR_EXISTS) ../build/al-anvar1.0.0 || $(MKDIR) ../build/al-anvar1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) ../build/al-anvar1.0.0/ && $(COPY_FILE) --parents anvar.h tools.h sqlite3.h database.h dbsearch.h quranwidget.h setting.h dbtreeview.h dbmodel.h findreplace.h player.h Downloader.h helpWindow.h addons.h ayeexplor.h langdialog.h sendermail/SmtpMime sendermail/smtpclient.h sendermail/quotedprintable.h sendermail/mimetext.h sendermail/mimepart.h sendermail/mimemessage.h sendermail/mimeinlinefile.h sendermail/mimehtml.h sendermail/mimefile.h sendermail/mimeattachment.h sendermail/emailaddress.h contactform.h moshafwidget.h editordering.h adddirdialog.h ../build/al-anvar1.0.0/ && $(COPY_FILE) --parents rc.qrc ../build/al-anvar1.0.0/ && $(COPY_FILE) --parents anvar.cpp main.cpp sqlite3.c setting.cpp addons.cpp ayeexplor.cpp langdialog.cpp sendermail/smtpclient.cpp sendermail/quotedprintable.cpp sendermail/mimetext.cpp sendermail/mimepart.cpp sendermail/mimemessage.cpp sendermail/mimeinlinefile.cpp sendermail/mimehtml.cpp sendermail/mimefile.cpp sendermail/mimeattachment.cpp sendermail/emailaddress.cpp contactform.cpp moshafwidget.cpp editordering.cpp adddirdialog.cpp ../build/al-anvar1.0.0/ && $(COPY_FILE) --parents anvar.ui setting.ui addons.ui ayeexplor.ui langdialog.ui player.ui quranwidget.ui contactform.ui moshafwidget.ui editordering.ui adddirdialog.ui ../build/al-anvar1.0.0/ && (cd `dirname ../build/al-anvar1.0.0` && $(TAR) al-anvar1.0.0.tar al-anvar1.0.0 && $(COMPRESS) al-anvar1.0.0.tar) && $(MOVE) `dirname ../build/al-anvar1.0.0`/al-anvar1.0.0.tar.gz . && $(DEL_FILE) -r ../build/al-anvar1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: ../build/moc_anvar.cpp ../build/moc_tools.cpp ../build/moc_dbsearch.cpp ../build/moc_quranwidget.cpp ../build/moc_setting.cpp ../build/moc_dbtreeview.cpp ../build/moc_dbmodel.cpp ../build/moc_findreplace.cpp ../build/moc_player.cpp ../build/moc_Downloader.cpp ../build/moc_helpWindow.cpp ../build/moc_addons.cpp ../build/moc_ayeexplor.cpp ../build/moc_langdialog.cpp ../build/moc_smtpclient.cpp ../build/moc_quotedprintable.cpp ../build/moc_mimepart.cpp ../build/moc_mimehtml.cpp ../build/moc_mimefile.cpp ../build/moc_mimeattachment.cpp ../build/moc_emailaddress.cpp ../build/moc_contactform.cpp ../build/moc_moshafwidget.cpp ../build/moc_editordering.cpp ../build/moc_adddirdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ../build/moc_anvar.cpp ../build/moc_tools.cpp ../build/moc_dbsearch.cpp ../build/moc_quranwidget.cpp ../build/moc_setting.cpp ../build/moc_dbtreeview.cpp ../build/moc_dbmodel.cpp ../build/moc_findreplace.cpp ../build/moc_player.cpp ../build/moc_Downloader.cpp ../build/moc_helpWindow.cpp ../build/moc_addons.cpp ../build/moc_ayeexplor.cpp ../build/moc_langdialog.cpp ../build/moc_smtpclient.cpp ../build/moc_quotedprintable.cpp ../build/moc_mimepart.cpp ../build/moc_mimehtml.cpp ../build/moc_mimefile.cpp ../build/moc_mimeattachment.cpp ../build/moc_emailaddress.cpp ../build/moc_contactform.cpp ../build/moc_moshafwidget.cpp ../build/moc_editordering.cpp ../build/moc_adddirdialog.cpp
../build/moc_anvar.cpp: setting.h \
		../build/ui_setting.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		quranwidget.h \
		database.h \
		player.h \
		Downloader.h \
		../build/ui_player.h \
		findreplace.h \
		ayeexplor.h \
		../build/ui_ayeexplor.h \
		dbtreeview.h \
		dbmodel.h \
		dbsearch.h \
		editordering.h \
		../build/ui_editordering.h \
		adddirdialog.h \
		../build/ui_adddirdialog.h \
		../build/ui_quranwidget.h \
		contactform.h \
		../build/ui_contactform.h \
		helpWindow.h \
		addons.h \
		../build/ui_addons.h \
		anvar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) anvar.h -o ../build/moc_anvar.cpp

../build/moc_tools.cpp: sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		tools.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tools.h -o ../build/moc_tools.cpp

../build/moc_dbsearch.cpp: database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		dbsearch.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dbsearch.h -o ../build/moc_dbsearch.cpp

../build/moc_quranwidget.cpp: database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		player.h \
		Downloader.h \
		../build/ui_player.h \
		findreplace.h \
		ayeexplor.h \
		../build/ui_ayeexplor.h \
		dbtreeview.h \
		dbmodel.h \
		dbsearch.h \
		editordering.h \
		../build/ui_editordering.h \
		adddirdialog.h \
		../build/ui_adddirdialog.h \
		../build/ui_quranwidget.h \
		contactform.h \
		../build/ui_contactform.h \
		quranwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) quranwidget.h -o ../build/moc_quranwidget.cpp

../build/moc_setting.cpp: ../build/ui_setting.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		setting.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) setting.h -o ../build/moc_setting.cpp

../build/moc_dbtreeview.cpp: dbmodel.h \
		database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		dbsearch.h \
		editordering.h \
		../build/ui_editordering.h \
		adddirdialog.h \
		../build/ui_adddirdialog.h \
		dbtreeview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dbtreeview.h -o ../build/moc_dbtreeview.cpp

../build/moc_dbmodel.cpp: database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		dbsearch.h \
		editordering.h \
		../build/ui_editordering.h \
		dbmodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dbmodel.h -o ../build/moc_dbmodel.cpp

../build/moc_findreplace.cpp: tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		findreplace.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) findreplace.h -o ../build/moc_findreplace.cpp

../build/moc_player.cpp: database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		Downloader.h \
		../build/ui_player.h \
		player.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) player.h -o ../build/moc_player.cpp

../build/moc_Downloader.cpp: tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		Downloader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Downloader.h -o ../build/moc_Downloader.cpp

../build/moc_helpWindow.cpp: findreplace.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		helpWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) helpWindow.h -o ../build/moc_helpWindow.cpp

../build/moc_addons.cpp: database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		Downloader.h \
		../build/ui_addons.h \
		addons.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) addons.h -o ../build/moc_addons.cpp

../build/moc_ayeexplor.cpp: ../build/ui_ayeexplor.h \
		dbtreeview.h \
		dbmodel.h \
		database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		dbsearch.h \
		editordering.h \
		../build/ui_editordering.h \
		adddirdialog.h \
		../build/ui_adddirdialog.h \
		findreplace.h \
		ayeexplor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ayeexplor.h -o ../build/moc_ayeexplor.cpp

../build/moc_langdialog.cpp: tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		langdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) langdialog.h -o ../build/moc_langdialog.cpp

../build/moc_smtpclient.cpp: sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/smtpclient.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sendermail/smtpclient.h -o ../build/moc_smtpclient.cpp

../build/moc_quotedprintable.cpp: sendermail/quotedprintable.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sendermail/quotedprintable.h -o ../build/moc_quotedprintable.cpp

../build/moc_mimepart.cpp: sendermail/mimepart.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sendermail/mimepart.h -o ../build/moc_mimepart.cpp

../build/moc_mimehtml.cpp: sendermail/mimetext.h \
		sendermail/mimepart.h \
		sendermail/mimehtml.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sendermail/mimehtml.h -o ../build/moc_mimehtml.cpp

../build/moc_mimefile.cpp: sendermail/mimepart.h \
		sendermail/mimefile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sendermail/mimefile.h -o ../build/moc_mimefile.cpp

../build/moc_mimeattachment.cpp: sendermail/mimepart.h \
		sendermail/mimefile.h \
		sendermail/mimeattachment.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sendermail/mimeattachment.h -o ../build/moc_mimeattachment.cpp

../build/moc_emailaddress.cpp: sendermail/emailaddress.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sendermail/emailaddress.h -o ../build/moc_emailaddress.cpp

../build/moc_contactform.cpp: ../build/ui_contactform.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		contactform.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) contactform.h -o ../build/moc_contactform.cpp

../build/moc_moshafwidget.cpp: database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		../build/ui_moshafwidget.h \
		player.h \
		Downloader.h \
		../build/ui_player.h \
		contactform.h \
		../build/ui_contactform.h \
		moshafwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) moshafwidget.h -o ../build/moc_moshafwidget.cpp

../build/moc_editordering.cpp: ../build/ui_editordering.h \
		database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		editordering.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) editordering.h -o ../build/moc_editordering.cpp

../build/moc_adddirdialog.cpp: ../build/ui_adddirdialog.h \
		adddirdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) adddirdialog.h -o ../build/moc_adddirdialog.cpp

compiler_rcc_make_all: qrc_rc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_rc.cpp
qrc_rc.cpp: rc.qrc \
		addonse-0.5.0.xml \
		Data.sql \
		language/English.xml \
		language/Arabic.xml \
		language/persian.xml \
		redist/irsans.ttf \
		redist/noorehira.ttf \
		redist/ScheherazadeRegOT.ttf \
		images/pause.png \
		images/folder.png \
		images/exit-icon.png \
		images/configureToolbar-icon.png \
		images/radiobutton_unchecked_hover.png \
		images/logo.png \
		images/right.png \
		images/delete.png \
		images/radiobutton_checked.png \
		images/help.png \
		images/radiobutton_unchecked.png \
		images/quran.png \
		images/checkbox_checked_pressed.png \
		images/checkbox_unchecked_pressed.png \
		images/sorah.png \
		images/downloading.gif \
		images/checkbox_unchecked.png \
		images/find-icon.png \
		images/playback.png \
		images/spinup.png \
		images/toTop.png \
		images/spinup_hover.png \
		images/spindown.png \
		images/subject.png \
		images/checkbox_checked.png \
		images/Explanations.png \
		images/checkbox_unchecked_hover.png \
		images/up_arrow_disabled.png \
		images/frame.png \
		images/tag.png \
		images/backup.png \
		images/Next.png \
		images/top.png \
		images/save-icon.png \
		images/play.png \
		images/add.png \
		images/layoutdelete.png \
		images/delete.ico \
		images/radiobutton_unchecked_pressed.png \
		images/top_right.png \
		images/app.png \
		images/fileprint.png \
		images/spindown_pressed.png \
		images/Download.png \
		images/previous-icon.png \
		images/Previous.png \
		images/filesave.png \
		images/checkbox_checked_hover.png \
		images/books.png \
		images/bot.png \
		images/move.png \
		images/toTrash.png \
		images/app.ico \
		images/down_arrow_disabled.png \
		images/radiobutton_checked_pressed.png \
		images/up_arrow.png \
		images/audio.png \
		images/comment_show.png \
		images/bg.png \
		images/spindown_hover.png \
		images/filteradd.png \
		images/about.png \
		images/search.png \
		images/bot_left.png \
		images/file.png \
		images/tree.png \
		images/home.png \
		images/down_arrow.png \
		images/font.png \
		images/comment_add.png \
		images/order.png \
		images/downarrow.png \
		images/exportpdf.png \
		images/b_048.png \
		images/top_left.png \
		images/bot_right.png \
		images/layoutadd.png \
		images/next-icon.png \
		images/color.png \
		images/spinup_off.png \
		images/ok.png \
		images/spindown_off.png \
		images/update.png \
		images/homepage.png \
		images/hizb.png \
		images/newsletter.png \
		images/left.png \
		images/spinup_pressed.png \
		images/radiobutton_checked_hover.png \
		images/filterdelete.png \
		images/addones.png \
		images/expand.png \
		images/exportXml.png \
		images/juz.png \
		doc/al-anvar-manual.Farsi.html \
		doc/al-anvar-manual.English.html \
		Styles/Pro.css \
		Styles/default.css \
		Styles/simple.css
	/usr/bin/rcc -name rc rc.qrc -o qrc_rc.cpp

compiler_image_collection_make_all: ../build/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ../build/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ../build/ui_anvar.h ../build/ui_setting.h ../build/ui_addons.h ../build/ui_ayeexplor.h ../build/ui_langdialog.h ../build/ui_player.h ../build/ui_quranwidget.h ../build/ui_contactform.h ../build/ui_moshafwidget.h ../build/ui_editordering.h ../build/ui_adddirdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ../build/ui_anvar.h ../build/ui_setting.h ../build/ui_addons.h ../build/ui_ayeexplor.h ../build/ui_langdialog.h ../build/ui_player.h ../build/ui_quranwidget.h ../build/ui_contactform.h ../build/ui_moshafwidget.h ../build/ui_editordering.h ../build/ui_adddirdialog.h
../build/ui_anvar.h: anvar.ui
	/usr/bin/uic-qt4 anvar.ui -o ../build/ui_anvar.h

../build/ui_setting.h: setting.ui
	/usr/bin/uic-qt4 setting.ui -o ../build/ui_setting.h

../build/ui_addons.h: addons.ui
	/usr/bin/uic-qt4 addons.ui -o ../build/ui_addons.h

../build/ui_ayeexplor.h: ayeexplor.ui
	/usr/bin/uic-qt4 ayeexplor.ui -o ../build/ui_ayeexplor.h

../build/ui_langdialog.h: langdialog.ui
	/usr/bin/uic-qt4 langdialog.ui -o ../build/ui_langdialog.h

../build/ui_player.h: player.ui
	/usr/bin/uic-qt4 player.ui -o ../build/ui_player.h

../build/ui_quranwidget.h: quranwidget.ui
	/usr/bin/uic-qt4 quranwidget.ui -o ../build/ui_quranwidget.h

../build/ui_contactform.h: contactform.ui
	/usr/bin/uic-qt4 contactform.ui -o ../build/ui_contactform.h

../build/ui_moshafwidget.h: moshafwidget.ui
	/usr/bin/uic-qt4 moshafwidget.ui -o ../build/ui_moshafwidget.h

../build/ui_editordering.h: editordering.ui
	/usr/bin/uic-qt4 editordering.ui -o ../build/ui_editordering.h

../build/ui_adddirdialog.h: adddirdialog.ui
	/usr/bin/uic-qt4 adddirdialog.ui -o ../build/ui_adddirdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

../build/anvar.o: anvar.cpp anvar.h \
		setting.h \
		../build/ui_setting.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		quranwidget.h \
		database.h \
		player.h \
		Downloader.h \
		../build/ui_player.h \
		findreplace.h \
		ayeexplor.h \
		../build/ui_ayeexplor.h \
		dbtreeview.h \
		dbmodel.h \
		dbsearch.h \
		editordering.h \
		../build/ui_editordering.h \
		adddirdialog.h \
		../build/ui_adddirdialog.h \
		../build/ui_quranwidget.h \
		contactform.h \
		../build/ui_contactform.h \
		helpWindow.h \
		addons.h \
		../build/ui_addons.h \
		../build/ui_anvar.h \
		moshafwidget.h \
		../build/ui_moshafwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/anvar.o anvar.cpp

../build/main.o: main.cpp anvar.h \
		setting.h \
		../build/ui_setting.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		quranwidget.h \
		database.h \
		player.h \
		Downloader.h \
		../build/ui_player.h \
		findreplace.h \
		ayeexplor.h \
		../build/ui_ayeexplor.h \
		dbtreeview.h \
		dbmodel.h \
		dbsearch.h \
		editordering.h \
		../build/ui_editordering.h \
		adddirdialog.h \
		../build/ui_adddirdialog.h \
		../build/ui_quranwidget.h \
		contactform.h \
		../build/ui_contactform.h \
		helpWindow.h \
		addons.h \
		../build/ui_addons.h \
		langdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/main.o main.cpp

../build/sqlite3.o: sqlite3.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../build/sqlite3.o sqlite3.c

../build/setting.o: setting.cpp setting.h \
		../build/ui_setting.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/setting.o setting.cpp

../build/addons.o: addons.cpp addons.h \
		database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		Downloader.h \
		../build/ui_addons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/addons.o addons.cpp

../build/ayeexplor.o: ayeexplor.cpp ayeexplor.h \
		../build/ui_ayeexplor.h \
		dbtreeview.h \
		dbmodel.h \
		database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		dbsearch.h \
		editordering.h \
		../build/ui_editordering.h \
		adddirdialog.h \
		../build/ui_adddirdialog.h \
		findreplace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/ayeexplor.o ayeexplor.cpp

../build/langdialog.o: langdialog.cpp langdialog.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		../build/ui_langdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/langdialog.o langdialog.cpp

../build/smtpclient.o: sendermail/smtpclient.cpp sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/smtpclient.o sendermail/smtpclient.cpp

../build/quotedprintable.o: sendermail/quotedprintable.cpp sendermail/quotedprintable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/quotedprintable.o sendermail/quotedprintable.cpp

../build/mimetext.o: sendermail/mimetext.cpp sendermail/mimetext.h \
		sendermail/mimepart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/mimetext.o sendermail/mimetext.cpp

../build/mimepart.o: sendermail/mimepart.cpp sendermail/mimepart.h \
		sendermail/quotedprintable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/mimepart.o sendermail/mimepart.cpp

../build/mimemessage.o: sendermail/mimemessage.cpp sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/quotedprintable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/mimemessage.o sendermail/mimemessage.cpp

../build/mimeinlinefile.o: sendermail/mimeinlinefile.cpp sendermail/mimeinlinefile.h \
		sendermail/mimefile.h \
		sendermail/mimepart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/mimeinlinefile.o sendermail/mimeinlinefile.cpp

../build/mimehtml.o: sendermail/mimehtml.cpp sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimepart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/mimehtml.o sendermail/mimehtml.cpp

../build/mimefile.o: sendermail/mimefile.cpp sendermail/mimefile.h \
		sendermail/mimepart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/mimefile.o sendermail/mimefile.cpp

../build/mimeattachment.o: sendermail/mimeattachment.cpp sendermail/mimeattachment.h \
		sendermail/mimepart.h \
		sendermail/mimefile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/mimeattachment.o sendermail/mimeattachment.cpp

../build/emailaddress.o: sendermail/emailaddress.cpp sendermail/emailaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/emailaddress.o sendermail/emailaddress.cpp

../build/contactform.o: contactform.cpp contactform.h \
		../build/ui_contactform.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/contactform.o contactform.cpp

../build/moshafwidget.o: moshafwidget.cpp moshafwidget.h \
		database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h \
		../build/ui_moshafwidget.h \
		player.h \
		Downloader.h \
		../build/ui_player.h \
		contactform.h \
		../build/ui_contactform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moshafwidget.o moshafwidget.cpp

../build/editordering.o: editordering.cpp editordering.h \
		../build/ui_editordering.h \
		database.h \
		tools.h \
		sqlite3.h \
		sendermail/SmtpMime \
		sendermail/smtpclient.h \
		sendermail/mimemessage.h \
		sendermail/mimepart.h \
		sendermail/emailaddress.h \
		sendermail/mimehtml.h \
		sendermail/mimetext.h \
		sendermail/mimeattachment.h \
		sendermail/mimefile.h \
		sendermail/mimeinlinefile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/editordering.o editordering.cpp

../build/adddirdialog.o: adddirdialog.cpp adddirdialog.h \
		../build/ui_adddirdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/adddirdialog.o adddirdialog.cpp

../build/moc_anvar.o: ../build/moc_anvar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_anvar.o ../build/moc_anvar.cpp

../build/moc_tools.o: ../build/moc_tools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_tools.o ../build/moc_tools.cpp

../build/moc_dbsearch.o: ../build/moc_dbsearch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_dbsearch.o ../build/moc_dbsearch.cpp

../build/moc_quranwidget.o: ../build/moc_quranwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_quranwidget.o ../build/moc_quranwidget.cpp

../build/moc_setting.o: ../build/moc_setting.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_setting.o ../build/moc_setting.cpp

../build/moc_dbtreeview.o: ../build/moc_dbtreeview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_dbtreeview.o ../build/moc_dbtreeview.cpp

../build/moc_dbmodel.o: ../build/moc_dbmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_dbmodel.o ../build/moc_dbmodel.cpp

../build/moc_findreplace.o: ../build/moc_findreplace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_findreplace.o ../build/moc_findreplace.cpp

../build/moc_player.o: ../build/moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_player.o ../build/moc_player.cpp

../build/moc_Downloader.o: ../build/moc_Downloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_Downloader.o ../build/moc_Downloader.cpp

../build/moc_helpWindow.o: ../build/moc_helpWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_helpWindow.o ../build/moc_helpWindow.cpp

../build/moc_addons.o: ../build/moc_addons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_addons.o ../build/moc_addons.cpp

../build/moc_ayeexplor.o: ../build/moc_ayeexplor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_ayeexplor.o ../build/moc_ayeexplor.cpp

../build/moc_langdialog.o: ../build/moc_langdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_langdialog.o ../build/moc_langdialog.cpp

../build/moc_smtpclient.o: ../build/moc_smtpclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_smtpclient.o ../build/moc_smtpclient.cpp

../build/moc_quotedprintable.o: ../build/moc_quotedprintable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_quotedprintable.o ../build/moc_quotedprintable.cpp

../build/moc_mimepart.o: ../build/moc_mimepart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_mimepart.o ../build/moc_mimepart.cpp

../build/moc_mimehtml.o: ../build/moc_mimehtml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_mimehtml.o ../build/moc_mimehtml.cpp

../build/moc_mimefile.o: ../build/moc_mimefile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_mimefile.o ../build/moc_mimefile.cpp

../build/moc_mimeattachment.o: ../build/moc_mimeattachment.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_mimeattachment.o ../build/moc_mimeattachment.cpp

../build/moc_emailaddress.o: ../build/moc_emailaddress.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_emailaddress.o ../build/moc_emailaddress.cpp

../build/moc_contactform.o: ../build/moc_contactform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_contactform.o ../build/moc_contactform.cpp

../build/moc_moshafwidget.o: ../build/moc_moshafwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_moshafwidget.o ../build/moc_moshafwidget.cpp

../build/moc_editordering.o: ../build/moc_editordering.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_editordering.o ../build/moc_editordering.cpp

../build/moc_adddirdialog.o: ../build/moc_adddirdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/moc_adddirdialog.o ../build/moc_adddirdialog.cpp

../build/qrc_rc.o: qrc_rc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/qrc_rc.o qrc_rc.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "../bin/$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_icons: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/pixmaps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 
	-$(INSTALL_PROGRAM) /home/hosein/Al-Anavr-master/redist/icons/alanvar.png $(INSTALL_ROOT)/usr/share/pixmaps/
	-strip $(INSTALL_ROOT)/usr/share/pixmaps/alanvar.png


uninstall_icons:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/alanvar.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 


install_icons2: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/app-install/icons/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/app-install/icons/ 
	-$(INSTALL_PROGRAM) /home/hosein/Al-Anavr-master/redist/icons/alanvar.png $(INSTALL_ROOT)/usr/share/app-install/icons/
	-strip $(INSTALL_ROOT)/usr/share/app-install/icons/alanvar.png


uninstall_icons2:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/app-install/icons/alanvar.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/app-install/icons/ 


install_desktops: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_PROGRAM) /home/hosein/Al-Anavr-master/redist/al-anvar.desktop $(INSTALL_ROOT)/usr/share/applications/
	-strip $(INSTALL_ROOT)/usr/share/applications/al-anvar.desktop


uninstall_desktops:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/al-anvar.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_desktops2: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/app-install/desktop/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/app-install/desktop/ 
	-$(INSTALL_PROGRAM) /home/hosein/Al-Anavr-master/redist/al-anvar.desktop $(INSTALL_ROOT)/usr/share/app-install/desktop/
	-strip $(INSTALL_ROOT)/usr/share/app-install/desktop/al-anvar.desktop


uninstall_desktops2:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/app-install/desktop/al-anvar.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/app-install/desktop/ 


install_fonts: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/ 
	-$(INSTALL_PROGRAM) /home/hosein/Al-Anavr-master/redist/irsans.ttf $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/
	-strip $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/irsans.ttf
	-$(INSTALL_PROGRAM) /home/hosein/Al-Anavr-master/redist/noorehira.ttf $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/
	-strip $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/noorehira.ttf
	-$(INSTALL_PROGRAM) /home/hosein/Al-Anavr-master/redist/ScheherazadeRegOT.ttf $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/
	-strip $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/ScheherazadeRegOT.ttf


uninstall_fonts:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/irsans.ttf 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/noorehira.ttf 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/ScheherazadeRegOT.ttf
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/fonts/truetype/font-al-anvar/ 


install:  install_target install_icons install_icons2 install_desktops install_desktops2 install_fonts  FORCE

uninstall: uninstall_target uninstall_icons uninstall_icons2 uninstall_desktops uninstall_desktops2 uninstall_fonts   FORCE

FORCE:

